### ISSUE TITLE
Cursor movement performance

### ISSUE THREAD

**Issue by romgrk** [f-person/git-blame.nvim#1]
Hey,

I was testing your plugin and when it's on, it feels like the cursor performance is degraded. There is a small flicker for each movement as well as the performance issue. Is this something you have noticed? Are you updating the info synchronously?

Thanks

**Comment by f-person** [comment]
Oh, didn't notice it. I think I know where the problem is, will fix it soon. Thanks!

**Comment by romgrk** [comment]
Still not usable enough for me but thanks.

IMHO this kind of plugin is better suited as a remote plugin, as it otherwise compromises keypress latency.

**Comment by romgrk** [comment]
Maybe if you're down to try out, these suggestions may improve the experience:
 - add the highlights asynchronously with `timer_start`, a small delay of like 5-10ms might help to make it feel more fluid
 - https://github.com/f-person/git-blame.nvim/blob/master/lua/gitblame/init.lua#L91-L96: use a binary search as it might be more efficient for large files

**Comment by f-person** [comment]
> there doesn't seem to be memory management when buffers are deleted

Yup, I thought about it too, it's in my plans :) Thanks for pointing that out anyways.

> add the info asynchronously with timer_start, a small delay of like 5-10ms might help to make it feel more fluid

I was doing research on this topic. Someone on Gitter recommended using vim.schedule, I did it, the performance seems to be improved. I'll tray using timer too.

> use a binary search
Oh, thanks! Didn't think about this one, will do it.

**Comment by f-person** [comment]
One more performance improvement that I'll implement is not continuing show_blame_info if the cursor was moved just horizontally, as it changes nothing.

**Comment by f-person** [comment]
Can you please try the [cursor-movement-performance](https://github.com/f-person/git-blame.nvim/tree/cursor-movement-performance) branch and see if it's better/good for you?

**Comment by f-person** [comment]
Also implemented memory management in https://github.com/f-person/git-blame.nvim/commit/82136e511be1f199e2938a6ba2c99cf8ee494f46

**Comment by romgrk** [comment]
I can't feel any performance issue anymore.
