### ISSUE TITLE
init error when update to a36b2

### ISSUE THREAD

**Issue by wangxuw** [f-person/git-blame.nvim#100]
* neovim version:0.8.0 lunarvim: v1.2 
* install this plugin using Packer
> NVIM v0.8.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.8.0/x86_64-redhat-linux-gnu/cmake.config -I/builddir/build/BUILD/neovim-0.8.0/src -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build/BUILD/neovim-0.8.0/x86_64-redhat-linux-gnu/src/nvim/auto -I/builddir/build/BUILD/neovim-0.8.0/x86_64-redhat-linux-gnu/include
Compiled by mockbuild@koji

* error msg:
<img width="1278" alt="image" src="https://github.com/f-person/git-blame.nvim/assets/10045739/382f9a3c-c765-42c4-ba60-ca5c593fe2c7">

The latest [commit](https://github.com/f-person/git-blame.nvim/commit/a36b277e527f9d34efe16c3636555ce0e0c0464c) adds _init.lua:308_ and this error encountered.

I am not familiar with lua, but I wonder if this error is related to the '#'?

**Comment by f-person** [comment]
What Neovim version are you on? `nvim_get_hl` was introduced in 0.9

**Comment by f-person** [comment]
Should we implement backward compatibility or mention the minimum version in README instead? 
@dhananjaylatkar any thoughts on this?

**Comment by dhananjaylatkar** [comment]
0.8.0 was released **one year ago** (Sept 2022). Any reason people are not upgrading?

If this is the only thing not compatible with 0.8.0 then it makes sense to change it.

**Comment by dhananjaylatkar** [comment]
There are 2 ways I can see -
1. Don't check if group is set or not. i.e do `nvim_set_hl()` all the time.
    Con: Too many calls to `nvim_set_set()`
2. Set hl group in `plugin/gitblame.vim` and then overwrite it in `require("gitblame").setup()`.
    This will give priority to lua config which should be okay since people won't be doing config using vimscript **_and_** lua.

**Comment by dhananjaylatkar** [comment]
2nd option is not working. Overwrite is not happening.

We can go with 1 or following workaround - 
```diff
diff --git a/lua/gitblame/init.lua b/lua/gitblame/init.lua
index c73e8a4..a6ed38d 100644
--- a/lua/gitblame/init.lua
+++ b/lua/gitblame/init.lua
@@ -305,14 +305,10 @@ local function update_blame_text(blame_text)

     local should_display_virtual_text = vim.g.gitblame_display_virtual_text == 1

-    if #vim.api.nvim_get_hl(0, { name = "gitblame" }) == 0 then
-        vim.api.nvim_set_hl(0, "gitblame", { link = vim.g.gitblame_highlight_group })
-    end
-
     if should_display_virtual_text then
         local options = {
             id = 1,
-            virt_text = { { blame_text, "gitblame" } },
+            virt_text = { { blame_text, vim.g.gitblame_highlight_group } },
             virt_text_win_col = virt_text_column,
         }
         local user_options = vim.g.gitblame_set_extmark_options or {}
```

**Comment by f-person** [comment]
@dhananjaylatkar I actually like this 🤔
Let me use that instead
