### ISSUE TITLE
E5108: Error executing lua Vim:E903: Process failed to start: too many open files: "/opt/homebrew/bin/fish"

### ISSUE THREAD

**Issue by kapral18** [f-person/git-blame.nvim#108]
When simply navigating through my config.fish file up and down I eventually get lags and then this error

![CleanShot 2023-10-16 at 12 52 10@2x](https://github.com/f-person/git-blame.nvim/assets/1625373/007d74ce-f8b4-4dc3-b390-38a8da786afc)

My fish folder is not git versioned.

Here is my config https://github.com/kapral18/config.nvim/blob/3db8ecb67be6f338cd97bc08f37b0cd2c665958d/lua/plugins/blame.lua#L4

**Comment by f-person** [comment]
Hi! Does this happen when you use the plugin outside the fish config, as well?

**Comment by kapral18** [comment]
> Hi! Does this happen when you use the plugin outside the fish config, as well?

No it actually only happens where there is no .git present

**Comment by kapral18** [comment]
I added 

```lua
    cond = function()
      -- check if .git directory exists
      local path = require("lazyvim.util").root.get() .. "/.git"
      local ok, err = vim.loop.fs_stat(path)
      return ok and ok.type == "directory"
    end,
```

to solve the problem for now, but I'd rather have this functionality builtin as with most other plugins, what do you think?

Also my code above doesn't take into account if you cwd
