### ISSUE TITLE
Commit message with `%` character causes lualine E539: Illegal character error

### ISSUE THREAD

**Issue by yungthai** [f-person/git-blame.nvim#109]
When showing a commit message on the lualine winbar or statusline:

```
      local git_blame = require("gitblame")

      opts.winbar = {
         lualine_c = {
           { git_blame.get_current_blame_text, cond = git_blame.is_blame_text_available },
          },
       }
```

It appears when navigating to any committed change that has a `%` character in its commit message, lualine will throw a E539: Illegal character error.

Steps to reproduce:

* Commit a change with message containing a `%` character e.g. "Fix % change calculation"
* (Possibly restart Neovim, as this plugin may not pick up the commit immediately)
* Navigate to the committed change to observe the lualine error.

This plugin may need "to escape `%` in it's output as they have special meaning in statusline".

**Comment by yungthai** [comment]
https://github.com/nvim-lualine/lualine.nvim/issues/873

**Comment by yungthai** [comment]
#https://github.com/SmiteshP/nvim-navic/issues/65

**Comment by yungthai** [comment]
This plugin already escapes the `%` character.

However, it's the adjacent character after the `%` (e.g. a space, quotation mark `"` or `'`, etc...) that causes the lualine E539 error.

Thus it's more suitable to further manipulate the commit message string within the user's lualine configuration.

Apology for the added noise.

**Comment by f-person** [comment]
> Apology for the added noise.

Hey! No problem! Maybe this will help someone who stumbles upon something similar sometime in the future :)
