### ISSUE TITLE
error when moving cursor

### ISSUE THREAD

**Issue by smartding** [f-person/git-blame.nvim#11]
I sometimes get an error when moving cursor:
```
Error detected while processing CursorMoved Autocommands for "*":
E5108: Error executing lua ../git-blame.nvim/lua/gitblame/init.lua:168: bad argument #2 to 'gsub' (string/funcion/table expected)
```
It doesn't happen every time I move my cursor, just occasionally.

**Comment by ecosse3** [comment]
I have the same after last update.

**Comment by f-person** [comment]
> I have the same after last update.

@ecosse3 Is it on line 168 for you too? If so, it means that info.summary is nil :thinking:

**Comment by f-person** [comment]
Blames are not loaded for files from kubernetes. git blame command outputs only filename. I think this might somehow be related to `luajob`.

**Comment by smartding** [comment]
> Blames are not loaded for files from kubernetes. git blame command outputs only filename. I think this might somehow be related to `luajob`.

blames are loaded for kubernetes files in my case.

**Comment by ecosse3** [comment]
@f-person Yes, but I got error for line 161 too.

![image](https://user-images.githubusercontent.com/17691791/100853120-b19cba80-3487-11eb-8e05-959243bd5981.png)

**Comment by smartding** [comment]
> @f-person Yes, but I got error for line 161 too.
> 
> ![image](https://user-images.githubusercontent.com/17691791/100853120-b19cba80-3487-11eb-8e05-959243bd5981.png)

I  got this error too today, so it's line 161 and 168

**Comment by f-person** [comment]
So `info.date` and `info.summary` are sometimes nil. Did this happen on an open-source repository? If so, can you please comment the repo link with file and line number on which the error occured?

**Comment by smartding** [comment]
> So `info.date` and `info.summary` are sometimes nil. Did this happen on an open-source repository? If so, can you please comment the repo link with file and line number on which the error occured?

here's an example where the line 168 errorr:
https://github.com/kubernetes/kubernetes/blob/5b8c3b90f3c74ba79f4bfa5be560d011694a7da0/pkg/kubelet/pod_workers.go#L183
the error occurs whenever I move my cursor on it.

**Comment by RTS5227** [comment]
```
Error detected while processing CursorMoved Autocommands for "*":                          
E5105: Error while calling lua chunk: ...config/nvim/plugged/git-blame.nvim/lua/gitblame/init.lua:92
: attempt to index field 'fn' (a nil value)
Press ENTER or type command to continue
```
How to fix it?

**Comment by f-person** [comment]
I guess `vim.fn` is not available in your version of Neovim. What version are you using btw? If you use nightly releases, the error should not occur.

**Comment by RTS5227** [comment]
> I guess `vim.fn` is not available in your version of Neovim. What version are you using btw? If you use nightly releases, the error should not occur.

NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
OS: Ubuntu 20.04.2 LTS x86_64
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

**Comment by smartding** [comment]
> > I guess `vim.fn` is not available in your version of Neovim. What version are you using btw? If you use nightly releases, the error should not occur.
> 
> NVIM v0.4.3
> Build type: Release
> LuaJIT 2.1.0-beta3
> OS: Ubuntu 20.04.2 LTS x86_64
> Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
> Compiled by [team+vim@tracker.debian.org](mailto:team+vim@tracker.debian.org)

this plugin requires neovim nightly version, which means 0.5. 
So 0.4.3 won't work.
