### ISSUE TITLE
Statusline integration is broken

### ISSUE THREAD

**Issue by jinzhongjia** [f-person/git-blame.nvim#110]
The last few commits seem to break this feature, I just updated to the latest configuration and it doesn't show up on lualine anymore, only at the end of the line

![image](https://github.com/f-person/git-blame.nvim/assets/41784264/a710c536-4f14-4101-ae22-45c830730982)

**Comment by f-person** [comment]
The plugin was recently migrated to fully use Lua, I assume that's related.
For now, could you try to see if the following works?

```lua
local git_blame = require("gitblame")
git_blame.setup({ display_virtual_text = false })
```

**Comment by jinzhongjia** [comment]
It does not display virtual text, but its statusline integration does not take effect either

**Comment by jinzhongjia** [comment]
![image](https://github.com/f-person/git-blame.nvim/assets/41784264/8477baca-dc7b-426b-a69c-933e0b785a0f)

**Comment by jinzhongjia** [comment]
Of course I rolled back to the previous commit and everything worked fine

**Comment by mihneamanolache** [comment]
+1

**Comment by jinzhongjia** [comment]
> +1 seems to work fine with commit [`e4dafc7`](https://github.com/f-person/git-blame.nvim/commit/e4dafc79cc7dcf4eec0547dbc6f3f3821b2f2b14)

Currently I also switch to this commit and it works normally, but subsequent commits do not work properly.

**Comment by Pagliacii** [comment]
This commit 65ce40cd00303ddbc63fc5e85a10cc39ed8d4727 turned function `get_current_blame_text` and `is_blame_text_available` into local functions. So it wasn't possible to access outside the init.lua.

**Comment by Pagliacii** [comment]
I am working on it.
