### ISSUE TITLE
gitblame_enabled stopped working

### ISSUE THREAD

**Issue by wolffberg** [f-person/git-blame.nvim#113]
`let g:gitblame_enabled=0` stopped working from `b6af0bd7821974c9a49a6d180c52ef691fe0f520`.

git-blame is installed using vim-plug and loaded without Lua in an `init.vim` file.

```
call plug#begin('~/.config/nvim/plugged')
Plug 'f-person/git-blame.nvim'
call plug#end()

let g:gitblame_enabled=0
nnoremap <leader>gb :GitBlameToggle<cr>
```

The toggle still works as expected but blame lines are always shown on nvim startup.

The only workaround I found so far was to pin the version to the last working commit (found by trial and error).

```
Plug 'f-person/git-blame.nvim', {'commit': 'b6af0bd7821974c9a49a6d180c52ef691fe0f520'}
```

**Comment by bossley9** [comment]
Hello, thanks for the heads up! Are you certain that commit is the last commit that the plugin was working? The commit right after that, https://github.com/f-person/git-blame.nvim/commit/4ff5874c80f25c5aaaaad8394eedbcb9f6b286cc, only adds a default value for a function. Can you verify that `b6af0bd7821974c9a49a6d180c52ef691fe0f520` works but `4ff5874c80f25c5aaaaad8394eedbcb9f6b286cc` doesn't work?

**Comment by wolffberg** [comment]
Sorry about that, I pasted the wrong line🤦‍♂️

Played around with the commits a bit more.

> This works as expected
> ```
> Plug 'f-person/git-blame.nvim', {'commit': 'e4dafc79cc7dcf4eec0547dbc6f3f3821b2f2b14'}
> ```

> From this commit, the plugin doesn't load at all
> ```
> Plug 'f-person/git-blame.nvim', {'commit': '65ce40cd00303ddbc63fc5e85a10cc39ed8d4727'}
> ```

> From this commit, blame is always enabled by default, ignoring `gitblame_enabled`
> ```
> Plug 'f-person/git-blame.nvim', {'commit': 'b6af0bd7821974c9a49a6d180c52ef691fe0f520'}
> ```

**Comment by bossley9** [comment]
Apologies for the late reply and thanks for the clarification! It looks like the recent change to remove Vimscript may have broken something: https://github.com/f-person/git-blame.nvim/pull/102

I'll take a look!
