### ISSUE TITLE
"not committed yet" for all lines?

### ISSUE THREAD

**Issue by smartding** [f-person/git-blame.nvim#12]
When I open a file as neovim command line argument, e.g. `nvim go.mod` in the kubernetes source tree, git-blames shows "not committed yet" for all lines in that buffer.

Usually this happens when:
1. open files as command line argument of neovim. If I open the same file after I start neovim, the commit message is loaded correctly.
1. in a large repo

**Comment by f-person** [comment]
Yes, I have this problem too. You can switch to an older version temporarily until it's solved.

**Comment by f-person** [comment]
It seems that I'm close to a solution for this issue.
