### ISSUE TITLE
Highlight depending on vim mode

### ISSUE THREAD

**Issue by vnva** [f-person/git-blame.nvim#122]
👋 Hello, is it possible to add a background change for gitblame when switching vim mode?
Thanks for your work.

[gitblame.webm](https://github.com/f-person/git-blame.nvim/assets/57404657/013c55a5-693f-43f2-ace9-1ba33d35b500)

**Comment by bossley9** [comment]
Hi! This plugin uses the `Comment` [highlight group](https://neovim.io/doc/user/syntax.html#highlight-groups) to render the color(s) of the blame. So if you want to change the blame color on mode change you could write a little lua configuration to do that:

```lua
vim.api.nvim_create_autocmd({ 'ModeChanged' }, {
    pattern = { '*' },
    callback = function()
        local mode = vim.fn.mode()
        if mode == 'n' then -- normal mode
            vim.cmd [[highlight Comment ctermbg=12 ctermfg=0]]
        elseif mode == 'V' then -- visual mode
            vim.cmd [[highlight Comment ctermbg=15 ctermfg=0]]
        end
    end
})
```

Which would look kinda like this:

https://github.com/f-person/git-blame.nvim/assets/35381535/7de6a9ea-1076-4d99-9dba-c0d10f0ddd45

You can also [change the default highlight group](https://github.com/f-person/git-blame.nvim/?tab=readme-ov-file#highlight-group). Does that answer your question?

**Comment by vnva** [comment]
Yes, thanks a lot!
