### ISSUE TITLE
More like a question: how would you deal with virtual text being displayed past the window borders ?

### ISSUE THREAD

**Issue by ginolegigot** [f-person/git-blame.nvim#141]
Hello,
Love the plugin so far but i have an issue i dont know how to fix, maybe it's because i'm a neovim newbie, but if the considered line of code is quite long and your neovim window is small (cuz many splits for example), the virtual text showed by git blame would vanished past the window/split borders and i dont know how to retrieve it to read it fully. I can't scroll it either.
Example: 
![image](https://github.com/user-attachments/assets/4bd86261-f2ae-4fce-9836-b02ac608103b)
we only see the author of plugin, but can't see the date and commit message because it's displayed past the window border

**Comment by msdone-lwt** [comment]
I usually use git-blame and gitsigns together. Gitsigns has a feature: blame_line, which can solve your problem

**Comment by ginolegigot** [comment]
Thanks for the share

**Comment by x93008** [comment]
Displaying submitted information is the main scenario I use this plugin for. If it can tolerate truncation, what do you do with this plugin?
