### ISSUE TITLE
blame info don't resume to show after leaving insert mode until moving

### ISSUE THREAD

**Issue by xaljer** [f-person/git-blame.nvim#16]
`CursorMovedI` clear the virtual text, and this code inhibit to show blame:
 ```
    if last_position.filepath == filepath and last_position.line == line then
        return
    end
```
When do we need the last_position?

**Comment by f-person** [comment]
> When do we need the last_position?

It's used to check if the cursor was moved vertically and, if so, do nothing. This is an issue though.

**Comment by onsails** [comment]
I have the same problem. 
Also in normal mode when I just open file, I see virtual text. After going to the next line by pressing j virtual text disappears.

**Comment by onsails** [comment]
```
:GitBlameToggle
:GitBlameToggle
```

Calling this command (twice) fixes the problem.

**Comment by fredrikaverpil** [comment]
I'm not sure what was done to fix this issue, but I still have to run the command twice for the blame to show.
