### ISSUE TITLE
Error on specific line

### ISSUE THREAD

**Issue by trebaud** [f-person/git-blame.nvim#19]
Hi great work btw!
I get this error on random lines from time to time:
```
 Error executing lua ...config/nvim/plugged/git-blame.nvim/lua/gitblame/init.lua:168: bad argument #2 to 'gsub' (string/function/table expected)

**Comment by f-person** [comment]
Hi, thanks!

Do you get that error with the latest version? Because I can see in your dotfiles that you are using the `file-open-performance` branch however it was merged to master 13 commits ago and many things changed since then :)

**Comment by trebaud** [comment]
Oh perfect 😄 thanks for taking the time of going through my dotfiles 🙏

**Comment by f-person** [comment]
I guess I can close the issue then. Feel free to reopen it or create a new one if something goes wrong ;)
