### ISSUE TITLE
Allow to change highlight group

### ISSUE THREAD

**Issue by weilbith** [f-person/git-blame.nvim#2]
Thanks for this cool plugin!
It would be pretty cool if you could make the highlight group configurable. I saw that it is linked to `Comment` for now.

**Comment by f-person** [comment]
You can change it by adding this to your init.vim:

```vim
highlight default link gitblame Visual
```

**Comment by weilbith** [comment]
Okay. But I guess I need to make sure this is set after the plugin got loaded. Correct?

**Comment by f-person** [comment]
Yep, if the plugin is loaded after init.vim is read, highlight group will most probably be overwritten. Yeah, I think it would be cool to add a variable for that. Thanks for the suggestion, will do :)

**Comment by weilbith** [comment]
Btw (I haven't tried it yet, still mobile), have you thought about how this interferes with the LSP diagnostic errors or linter messages?

**Comment by f-person** [comment]
It should have conflicts with the default behavior of LSP error messages and warnings, I'm using I'm using [diagnostic-nvim](https://github.com/nvim-lua/diagnostic-nvim), errors and warnings are displayed in a popup window for me instead of being added to virtual text.

**Comment by f-person** [comment]
Looked it up, you can set it like this:
```vim
highlight gitblame YourHighlightGroup
```

I set the default value for highlight group here:
https://github.com/f-person/git-blame.nvim/blob/24c45e0cc913a3b733dba550ecd30c180214e702/plugin/gitblame.vim#L2

If it is already set (from init.vim for example), your value won't be overwriten.

**Comment by weilbith** [comment]
Alright. Thanks for your help!
It reminded me also to rethink/update my diagnostics handling.
