### ISSUE TITLE
nvim_create_namespace could be used to create the hl-id

### ISSUE THREAD

**Issue by theHamsta** [f-person/git-blame.nvim#21]
I guess this is usually no problem. But it would be  safer to use `vim.api.nvim_create_namespace` to reserve a hl_namespace exclusive for this plugin

https://github.com/theHamsta/nvim-dap-virtual-text/issues/3#issuecomment-801272811

**Comment by f-person** [comment]
Thanks a lot for the suggestion. Yup, I think it's not something that happens often but the safer the better. I'll try to find time for this issue today.
