### ISSUE TITLE
Feature request: Virtual text position options

### ISSUE THREAD

**Issue by andersevenrud** [f-person/git-blame.nvim#24]
I'd love to see an option to set the blame virtual text to render from the edge of the window instead of at the end of the line.

End of line (current):

![before](https://user-images.githubusercontent.com/161548/112741629-c1389580-8f87-11eb-8986-6beea2a80d49.png)

Edge of window (requested):

![after](https://user-images.githubusercontent.com/161548/112741631-c72e7680-8f87-11eb-91a0-defeb214293c.png)

**Comment by andersevenrud** [comment]
Silly me, I didn't look through the issues closely enough as there's a *closed* issue about this: https://github.com/f-person/git-blame.nvim/issues/23 that you said will be re-opened when https://github.com/neovim/neovim/issues/11634 lands. Might wanna consider keeping that #23 open so that you don't get another one of these :blush:

**Comment by f-person** [comment]
Yes, you're right. I'm going to open it.
