### ISSUE TITLE
Option to show blame in statusLine instead of virtualText

### ISSUE THREAD

**Issue by vipulmathur** [f-person/git-blame.nvim#27]
Thanks for this fast plugin!

Could you please add an option to show the blame in the `statusLine` instead of `virtualText`?

This is to allow keeping the blame text from interfering with the main code view. For now, I am relying on toggling blame on and off.

**Comment by f-person** [comment]
Do you know if functionality for writing to status line is built into neovim or I should integrate with third-party plugins in order to implement this?

**Comment by Einenlum** [comment]
Nice idea!
Maybe it would be possible to simply return the output like nvim-gps [does](https://github.com/SmiteshP/nvim-gps#-usage) ?

**Comment by f-person** [comment]
Yup, asked on Reddit and they suggested this approach too. I'll implement it when I find some time. Unfortunately, too busy right now :)

**Comment by Einenlum** [comment]
I have started but I'm still struggling with the plugin being initialized on `GitBlameEnable` and the fact that we need to access the plugin later to get the functions (fetching the current state) for the status line.

My current work: https://github.com/f-person/git-blame.nvim/compare/master...Einenlum:feature/allow-printing-blame-in-status?expand=1

**Comment by f-person** [comment]
Why do we need `is_blame_info_available`? I think we can just return an empty string if there's no blame info currently

**Comment by Einenlum** [comment]
@f-person Seems like most status lines decide if they should display the text based on a bool condition.
For sure you could just print an empty text, but in some cases it can be nice to know if the information is available because the space on the status line is quite limited.
For example, I use nvim-gps to know where I am in the file, but I would like it to appear only if there is no git blame activated.

**Comment by f-person** [comment]
Finally managed to implement this!
@vipulmathur thank you for the suggestion!
@Einenlum thank you for your ideas and reference to `nvim-gps`!

<3
