### ISSUE TITLE
Include support for untracked files

### ISSUE THREAD

**Issue by lcrockett** [f-person/git-blame.nvim#30]
Cheers on the plugin. Blame lines are rapidly showing up, something that `git-blame` does better than other alternatives.

Would you be interested in adding support to show blame lines for untracked git files as well ? I've seen these being included with another plugin and found it helpful to know that the buffer you're working in is part of a git repository as it would show the changes are uncommited.

**Comment by f-person** [comment]
Sounds good. I think this should be configurable.

**Comment by f-person** [comment]
@lcrockett what should the plugin show in untracked files? I checked VS Code's GitLens and it doesn't show anything

**Comment by lcrockett** [comment]
What about simply showing `﻿Not Committed Yet` ? I think that's what `lewis6991/gitsigns.nvim` is doing.

**Comment by lcrockett** [comment]
I've tested it and it works right out-of-the-box, cheers on the added feature !
