### ISSUE TITLE
Incorrect output on last line of file without a line ending

### ISSUE THREAD

**Issue by donovan** [f-person/git-blame.nvim#31]
This plugin gives the incorrect output (`Not Committed Yet`) on the last line of a file that is missing a line ending.

To reproduce find a file without a line end on the final line:

```
$ rg -l '[^\n]\z'
``` 

Open the file, (`nvim file`) enable the plugin if required (`:GitBlameToggle`), hit `G`. The blame line says `Not Committed Yet`. Quit (`:q`) and run git blame on the file (`git blame file | tail -n 1`), line shows commit (assuming you didn't actually open a file with an uncommitted final line)

**Comment by f-person** [comment]
Thanks for the issue. I get blame lines from Neovim's Lua API and feed them to git. I tried to do some things but I was going in a wrong direction. I'll check the Lua API to see if it's possible to get the line with line endings.

**Comment by f-person** [comment]
I'll be happy if someone can help me get the lines with endings. Neovim APIs currently just return an array of lines

**Comment by f-person** [comment]
Hey @donovan! I just checked on my machine, and #48 seems to fix it. I am going to close the issue for now but feel free to repone it if you update the plugin, and the issue persists.
