### ISSUE TITLE
Virtual text overriding line highlight

### ISSUE THREAD

**Issue by camiloaromero23** [f-person/git-blame.nvim#32]
It was working fine with neovim stable(0.5). Today I updated to the unstable version (0.6) and my line highlight messed up. I hope you can fix this soon or help me with a workaround pls.
![image](https://user-images.githubusercontent.com/64717266/139329457-1e50687e-55bc-4e8a-aec7-55a580f04fa0.png)

**Comment by f-person** [comment]
This is an issue with Neovim. We should wait until it's fixed. Until then you can downgrade to 0.5 if this is critical for you.

**Comment by camiloaromero23** [comment]
neovim 0.6 just released and the issue persists. Maybe they dropped support for the feature mentioned above. Can you explain me the workaround pls?

**Comment by camiloaromero23** [comment]
Reading the issue, the added this bug to the 0.7 milestone 🤔

**Comment by f-person** [comment]
The only "workaround" that comes to my mind is just disabling either cursorline highlight or this plugin. This is an issue with Neovim itself, not `git-blame.nvim` so I don't think it's a good idea to come up with hacks to fix this.

**Comment by f-person** [comment]
@camiloaromero23 I am going to close this issue as I believe it's not related to this plugin and is a Neovim issue instead. Feel free to reopen it if you get to know a way to fix it from the plugin's side.

**Comment by camiloaromero23** [comment]
I came up with a solution to this issue by changing the `hl_mode` from the `set_extmark_options` to `combine`
``` lua
vim.g.gitblame_set_extmark_options = {
  hl_mode = "combine",
}
```
Hope this helps someone or that someone makes this value conditional if cursorline highlight is enabled.

<img width="1558" alt="image" src="https://user-images.githubusercontent.com/64717266/167989643-18085dd1-125d-4696-b346-2325cd1f69a4.png">

**Comment by f-person** [comment]
@camiloaromero23 good to hear it's fixed for you!

**Comment by frdwhite24** [comment]
Neovim v0.9.1 and the above solution from @camiloaromero23 is working perfectly to solve this issue!

**Comment by camiloaromero23** [comment]
@f-person What do you think about adding this fix to the README like in a FAQ section?

**Comment by dhananjaylatkar** [comment]
Why not add `hl_mode = "combine"` as default option? Does it break something else?

**Comment by f-person** [comment]
> Why not add `hl_mode = "combine"` as default option? Does it break something else?

Yup, this sounds like something worth trying. I'll check how this impacts the default behavior after checking the PRs :) 
(it's probably safe to add)
