### ISSUE TITLE
several 'git blame' spawned when scroll the cursor at plugin load

### ISSUE THREAD

**Issue by matteo-briani** [f-person/git-blame.nvim#34]
If I toggle git-blame and immediately move up and down the line with the cursor, I am experiencing several ```git blame``` command spawned by the plugin.
The commands do not ever resolve and the CPU gets used at 100%.
The only solution is to quit nvim.

Any idea why this is happening? I may cook a patch if pointed in the right direction.

**Comment by f-person** [comment]
Currently no ideas, I'll try to find some time to take a look at the issue.
Does this issue occur on all files? How large are the files?

**Comment by matteo-briani** [comment]
The file itself is small. The git repository is actually big. 
It happens on my laptop, which is a T440. 
I have never noticed this issue on more powerful machines. 
My guess is that if I let the plugin load completely before performing any actions, everything works fine.

**Comment by f-person** [comment]
>  My guess is that if I let the plugin load completely before performing any actions, everything works fine.

This is interesting. It doesn't depend on third-party plugins. It does use the Neovim's APIs though.

You mentioned before that you toggle the plugin. Do you do it by calling `GitBlameToggle` or in another way?

**Comment by f-person** [comment]
Which version of Neovim does this issue occur BTW?

**Comment by matteo-briani** [comment]
I am using Neovim v0.5.1. 
At the beginning I started experiencing this issue at startup, because the plugin was auto loading. 
Then, I disabled it and started experimenting toggling the plugin with ```GitBlameEnable```.

I can reproduce it by:
- enter Nvim with the plugin disabled
- load a file in a repo 
- turn on the plugin with ```GitBlameEnable``` and immediately press ```j``` or ```k``` to move up and down

If I give it the time to load properly, it does not happen, it just happen when I immediately move the cursor after turning on the plugin. 
The computer CPU get used at 100%, so I checked what happend on ```htop```, and I saw several ```git blame``` running.
My speculation is that the number of the spawned ```git blame``` is the same number of lines I move with the cursor; but I have not check thoroughly.

**Comment by f-person** [comment]
I just tried to reproduce it following your instructions but everything works fine for me 😕

**Comment by matteo-briani** [comment]
If you are willing to leave this issue open for a while I can try to investigate it further.

**Comment by f-person** [comment]
Sure, thank you!

**Comment by matteo-briani** [comment]
I got some time to spend on the issue and I found out that is not related to the plugin.
It had something to do with my ```fish``` shell and its latency on boot due to a polluted ```fish_user_paths``` variable.
Once I cleaned it, the issue disappeared. 
However, it is not clear to me why the issue was triggered when moving the cursor at the plugin startup.
Anyway, in the meanwhile, I would close the issue since it is not reproducible without a buggy ```fish``` configuration.
Thanks again for your time and this awesome plugin!

**Comment by grnnja** [comment]
I'm having the same problem when using git-blame with a big [repo](https://github.com/NixOS/nixpkgs). it takes a couple of seconds after opening neovim for the first git blame to show up. If I move the cursor during this time a bunch of git processes get spawned that take 100% of the cpu. It seems like the number of commits causes the slowdown and not the number of files or lines of code since [this repo](https://github.com/virejdasani/Commited) with a lot of commits but few lines code and files causes the same problem.

**Comment by matteo-briani** [comment]
I confirm it. 
Apparently it has to do with the amount of time ```git blame``` takes to run; regardless if it caused by a very long commit history or a long shell boot time (which was the case when I first noticed the issue).

**Comment by f-person** [comment]
Maybe I should add some logic to prevent this
