### ISSUE TITLE
Precedence of virtual text

### ISSUE THREAD

**Issue by hahuang65** [f-person/git-blame.nvim#36]
Is there any way to set what displays first in virtual text?
I have a case where there is an LSP diagnostic, but it always appears AFTER the git blame text.
I'd prefer it to be the other way around since an LSP diagnostic is usually more actionable than the git blame text.

Example:
![grim_01_11_22-13_33_36](https://user-images.githubusercontent.com/280972/149027670-3dc8ed9c-b633-46bd-b048-ef13df015495.png)

**Comment by f-person** [comment]
Perhaps `nvim_buf_set_virtual_text` should be migrated to [`nvim_buf_set_extmark`](https://neovim.io/doc/user/api.html#nvim_buf_set_extmark()) which has a `priority` option

**Comment by f-person** [comment]
@hahuang65 the plugin now uses `nvim_buf_set_extmark` and its options can be configured via `g:gitblame_set_extmark_options`. Please check if changing the priority solves your issue. A link to the documentation of the new configuration option – https://github.com/f-person/git-blame.nvim#nvim_buf_set_extmark-optional-parameters

**Comment by hahuang65** [comment]
@f-person thanks for implementing that! It does work. I had to pass in a value > 4100 to be after the LSP diagnostics.

Thanks agian!
