### ISSUE TITLE
GitBlameOpenCommitURL doesn't work

### ISSUE THREAD

**Issue by ic-768** [f-person/git-blame.nvim#39]
First off, awesome plugin! It's very useful and responsive.

However I can't seem to work out why the openCommitURL command won't work. 
I'm on a line that's having its commit blamed normally. I then run the command, and nothing happens. Is it supposed to open a browser tab to the url? Because it's not happening on my end.

**Comment by f-person** [comment]
If your operating system is not macOS, most likely it's fixed now. Please update to the latest version and see if it works now

See also #38

**Comment by ic-768** [comment]
I'm on Linux, and I fixed it locally by removing all the if-statements in the utils.lua file in the commit you linked to -  always running the xdg-open command. So I guess one of the if's is being triggered when it shouldn't.

I don't know any lua, so I'm not sure how I would debug this to help find the root of the problem. If you have any tips I'd be happy to try and help.
