### ISSUE TITLE
Copying the SHA of the line

### ISSUE THREAD

**Issue by balazser** [f-person/git-blame.nvim#41]
Hey Arshak,
Thank for the plugin!
Do you think it is possible somehow to put the `SHA` to the system clipboard or somewhere where I can take it to another terminal to see the `git show` etc.? :thinking:

**Comment by f-person** [comment]
While it's not currently possible, it's relatively easy to implement, so I'll get to it some day (perhaps on weekends) :)

**Comment by balazser** [comment]
wow, thanks!  We are looking forward to using it! :pray:

**Comment by f-person** [comment]
> it's relatively easy to implement

Oops, need to figure out a cross-platform way to copy stuff into clipboard :)

**Comment by f-person** [comment]
@balazser please update the plugin to latest version and see if the `:GitBlameCopySHA` command works for you
