### ISSUE TITLE
Disable in file tree viewer

### ISSUE THREAD

**Issue by AutodeskAbe** [f-person/git-blame.nvim#45]
I browsed the docs and hopefully I didn't miss it, but how do I disable blame in a file tree viewer? Thanks.

![Screen Shot 2022-03-25 at 2 24 57 PM](https://user-images.githubusercontent.com/93958092/160203237-88d0fe7e-1a09-4262-8c9c-f6b43d6da527.png)

**Comment by f-person** [comment]
Have you tried adding its filetype to `g:gitblame_ignored_filetypes`?

**Comment by f-person** [comment]
For NERDTree it's `"nerdtree"`
```vim
let g:gitblame_ignored_filetypes = ['nerdtree']
```

If you use something else and don't know the filetype of your viewer, you can get it via `:echo &filetype`

**Comment by lioaslan** [comment]
> For NERDTree it's `"nerdtree"`
> 
> ```viml
> let g:gitblame_ignored_filetypes = ['nerdtree']
> ```
> 
> If you use something else and don't know the filetype of your viewer, you can get it via `:echo &filetype`

Thanks for the solution. You should add this as an example to Readme because so many users use Nerdtree

**Comment by francois-pasquier** [comment]
For NvimTree and lua config it's: `vim.g.gitblame_ignored_filetypes = { "NvimTree" }`
