### ISSUE TITLE
Git blame should not blame in neovim explorer

### ISSUE THREAD

**Issue by brunobmello25** [f-person/git-blame.nvim#46]
When exploring a directory it should not git blame as a text file, but it does that. Screenshot below

![image](https://user-images.githubusercontent.com/29875060/163883829-1e5da41c-2552-402c-b672-260f5825a75f.png)

**Comment by f-person** [comment]
It can be disabled via `ignored_filetypes`. Please see #45

**Comment by brunobmello25** [comment]
indeed, apologies for the duplicate. I'll close this issue now.

Thanks!

**Comment by f-person** [comment]
Yay! I think, I should add ignore some filetypes by default (like explorer, nerdtree, etc)

**Comment by brunobmello25** [comment]
I agree! At least the default neovim explorer (the one I'm using)
