### ISSUE TITLE
Needs to be enabled to make the GitBlameCopySHA or GitBlameOpenCommitURL work

### ISSUE THREAD

**Issue by ranelpadon** [f-person/git-blame.nvim#47]
I disabled this plugin on startup since I don't want to have clutter:
```vim
let g:gitblame_enabled = 0
```

But when running `:GitBlameCopySHA` or `:GitBlameOpenCommitURL`, it will trigger this error and will not work:

<img width="804" alt="Screen Shot 2022-04-27 at 2 40 25 AM" src="https://user-images.githubusercontent.com/4292088/165371058-1d671537-f4e9-44f6-9313-92237803514c.png">

Apparently, I need to enable the plugin first (via `:GitBlameEnable` or `:GitBlameToggle`) before I could execute those 2 commands, which is not good UX I think. Ideally, the plugin should be enabled automatically when it's disabled before performing actions such as `:GitBlameCopySHA` or `:GitBlameOpenCommitURL`, then revert back to disabled after performing the actions.

I tried this also but it didn't work (same error):
```vim
function SampleFunc()
      :GitBlameEnable  " Make sure it's enabled.
      :GitBlameCopySHA
      :GitBlameDisable  " Revert back to disabled.
endfunction
nnoremap <Leader>gbs :call SampleFunc()<CR>
```

Am I missing something? Or could we have a flag/setting to have this kind of behavior? Thanks :)

**Comment by f-person** [comment]
Hi, thanks for the issue! Yup, the plugin doesn't load blames when it's disabled, that's why you get the exception. I think what you tried to do is the expected behavior and will fix it on weekends or sooner :)

**Comment by ranelpadon** [comment]
@f-person Confirmed to be working. Thanks a lot. :)
