### ISSUE TITLE
feat: blame column

### ISSUE THREAD

**Issue by jgollenz** [f-person/git-blame.nvim#50]
The problem: 

 - often times I have long lines and cannot even see the content of the blame anymore, as it is appended to that line and disappearing to the right.
 - I only see the blame of the current line I'm on. If I have a chunk of code it's useful to see at a glance e.g. if the whole thing was committed by the same person
 - due to the blame being appended, it's position jumps around horizontally a lot. I constantly have to readjust where I'm looking at

The solution:

Similar to the signcolumn that [gitgutter](https://github.com/airblade/vim-gitgutter) is using, this plugin could put the blame into a column to the left of the actual code. [CLion](https://www.jetbrains.com/help/clion/investigate-changes.html#annotate_blame) does it this way. Ofc, it probably is not very useful to throw the whole thing (author, full date, commit headline) in there, but a shortened date (dd-mm-yyyy) + the last name of the author would work well to see things at a glance. Even if adding such a column will result in the line being cut off to the right, I usually don't mind because I care more about seeing who did what at which point in time for all the lines I currently investigate.

**Comment by f-person** [comment]
Do you want something similar to what GitHub blame does?

![image](https://user-images.githubusercontent.com/31893391/172582607-d0a8f25b-b216-4563-8cc1-6eaf76e5fb6c.png)

**Comment by jgollenz** [comment]
Yes, although I personally don't care too much about the whole commit message. That is a matter of taste though and users should be able to configure the formatting the contents of the blame they want to display (like your plugin already offers)

**Comment by jgollenz** [comment]
What would also be cool, is if one could highlight all lines of code by the same person with the same color. I have seen this somewhere, but I cannot remember which ide/editor it was nor find any screenshot of it. I'll keep on searching. It's probably a different issue though

**Comment by liuerfire** [comment]
https://github.com/tpope/vim-fugitive can do this by `Git blame` cmd.
![image](https://user-images.githubusercontent.com/745867/187350574-ad6cbf12-7806-4646-8f07-c1f5db0531d2.png)

I also hope git-blame.nvim can have this feature for the people like me who do most git stuff by cli. So there's no necessary to install a plugin contains whole git features. :smile:

**Comment by jgollenz** [comment]
@liuerfire thank you very much! Yes, that's basically what I was looking for :+1:

**Comment by f-person** [comment]
Closing the issue since it's out of the scope of the package and vim-fugitive does support this behavior
