### ISSUE TITLE
Performance on big git projects

### ISSUE THREAD

**Issue by ivankovnatsky** [f-person/git-blame.nvim#52]
Thanks for working on the plugin. I like it.

In most cases I don't even bother, plugins works great, no performance impact whatsoever.

Though I noticed on huge projects like this one for example: https://github.com/NixOS/nixpkgs my laptop almost hangs, and I can relate to why.

So my first thought was can it auto-disable itself on huge git project. Maybe another way would be to change the workflow and toggle it manually, which is not really great, as I'm feeling used to it, once I tried it.

What do you think?

**Comment by f-person** [comment]
Most of the plugin should be asynchronous and non-blocking, however, some parts may still not be so (and that might be the problem). I'll try to debug how it works with the repo you mentioned and see if there's a way to improve it.

One thing that is different in this plugin is how it loads blame. Most of other plugins I've seen use the git blame command that displays a blame message for a particular line. However, `git-blame.nvim` loads blames for the whole file and decides which one to display whenever you move your cursor.

> my laptop almost hangs

Do you mean the OS stops responding or just nvim? Also, could you share your laptop specs and Neovim version?

**Comment by ivankovnatsky** [comment]
> One thing that is different in this plugin is how it loads blame. Most of other plugins I've seen use the git blame command that displays a blame message for a particular line. However, git-blame.nvim loads blames for the whole file and decides which one to display whenever you move your cursor.

:+1: 

To be more precise I probably did an extreme use-case opening files with:

```
nvim -p `rg something -l`
```

![image](https://user-images.githubusercontent.com/75213/176009672-9f916414-0a54-4be5-94c0-897cc578f8d0.png)

One instance of nvim in most cases working fine, but I think there once was slowness, which could not confirm currently. 

> Do you mean the OS stops responding or just nvim? Also, could you share your laptop specs and Neovim version?

i7 8 Core CPU / 16G / NVIM v0.7.0

It's hard to asses how to better tackle this, probably in my current case would be just to run nvim with `--noplugin`, but maybe there could be a wiser logic like checking for git history or something, just thoughts.

**Comment by f-person** [comment]
Hey! I wanted to investigate the issue, and realized that nixpkgs is 2+GB :o 
Do you know any other projects in which the plugin behaves like that?

**Comment by ivankovnatsky** [comment]
Hey. Looking back it looks like this plugin or any other would behave similarly in big/huge projects, at least with thousands of commits.

This file in particular would eat many resources trying to render blame commit: https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix.

Again, to revise plugin behaves really great with lazy-loading, and this use-case might too extreme. The huge file might just indicate not the greatest code/framework organization, if I can say that.

**Comment by f-person** [comment]
Okay, thanks for your time on investigating this anyways :)
Maybe someday we'll fix this, there should be a way ;)
