### ISSUE TITLE
Breaks when spaces in filepath

### ISSUE THREAD

**Issue by eriedaberrie** [f-person/git-blame.nvim#53]
Like the title says, the plugin works fine usually but ends up always saying "Not Committed Yet" whenever the filepath has spaces in it. It seems to be a fairly easy fix just by wrapping all the filepaths in vim.fn.shellescape().
(Maybe this is a sign that I should really stop using spaces in my git directory names.)

**Comment by f-person** [comment]
@eriedaberrie did #54 fix it for you? I tried the plugin on a file with spaces after merging #54 but got the same result. I'll try to do some more investigation later

**Comment by eriedaberrie** [comment]
That's strange, I was able to get everything working with #54.

**Comment by f-person** [comment]
True, works for me too. Thanks one more time ^_^
