### ISSUE TITLE
git blame ignores g:gitblame_enabled

### ISSUE THREAD

**Issue by xsteadfastx** [f-person/git-blame.nvim#55]
i installed gitblame through packer and config it in nvim through `vim.g.gitblame_enabled = 0`. But it will always show blame message on opening a file.

```
VIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az164-457
```

**Comment by f-person** [comment]
Interesting. I just tried to disable it in `init.lua` and it worked fine for me. Can you show the full config?

**Comment by f-person** [comment]
Closing the issue due to lack of response. Feel free to reopen if the problem persists ;)
