### ISSUE TITLE
"not committed yet" shows in nvim tree

### ISSUE THREAD

**Issue by stocks29** [f-person/git-blame.nvim#58]
It would be nice to not have this display for nvim tree.

<img width="262" alt="Screen Shot 2022-09-12 at 6 58 06 AM" src="https://user-images.githubusercontent.com/188319/189637048-3520405f-d5ce-4c97-bae2-21ccf135e189.png">

**Comment by f-person** [comment]
Hi, you can disable it via `g:gitblame_ignored_filetypes`. See also #45. It seems for NvimTree it is

```lua
-- Lua
vim.g.gitblame_ignored_filetypes = { "NvimTree" }
```

```vim
" Vim
let g:gitblame_ignored_filetypes = [ 'NvimTree' ]
```

**Comment by stocks29** [comment]
@f-person , thanks that worked perfectly! think it's worth making this the default?
