### ISSUE TITLE
how to set time zone

### ISSUE THREAD

**Issue by vintingb** [f-person/git-blame.nvim#62]
Hi, I try to set time zone to local zone,but I didn't found how to set

**Comment by f-person** [comment]
Hi, the plugin uses Lua's [os.date](https://www.lua.org/pil/22.1.html). I didn't find any info about customizing the timezone, but the computer's timezone should be used by default

**Comment by vintingb** [comment]
> Hi, the plugin uses Lua's [os.date](https://www.lua.org/pil/22.1.html). I didn't find any info about customizing the timezone, but the computer's timezone should be used by default

thanks, I think I should use relative time.
