### ISSUE TITLE
gitblame_enabled=0 not working in lunar vim

### ISSUE THREAD

**Issue by yannk** [f-person/git-blame.nvim#65]
Similar to #55 I see the configuration in lunar vimdocs not working

https://www.lunarvim.org/docs/plugins/extra-plugins#git-blame
```
lvim.plugins = {
    {
        "f-person/git-blame.nvim",
        event = "BufRead",
        config = function()
            vim.cmd "highlight default link gitblame SpecialComment"
            vim.g.gitblame_enabled = 0
        end,
    },
```

versions:
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-002.local
```

**Comment by f-person** [comment]
Hi! Thanks for your report! My guess is once the `config()` function is called, the plugin is already initialized which causes the problem. A hack, for now, would be calling `require('gitblame').disable()` in the lunar config. I'll check how I can solve this though

**Comment by f-person** [comment]
Hey! Would implementing #69 be good enough for this use case? I want to switch to a `setup` function style without breaking the current configurations, so I'm thinking about implementing `setup` that will configure everything required but setting `vim.g.gitblame_enabled` to `0` still won't work. When a `setup` function is implemented, I'll make a PR to `lunarvim` to update their docs to use `setup`.

**Comment by moizalicious** [comment]
For me calling `require('gitblame').disable()` does not work either.

Instead running `vim.cmd("GitBlameDisable")` works and disables git blame on startup.

Note: I am using regular NeoVim and not LunarVim.

**Comment by scott-b-gilbert** [comment]
I was having the same issue on neovim 0.9.  Running the cmd as @moizalicious indicated somewhat worked.  I was still getting one git blame on the first line of the first file that I opened.  :man_shrugging: 

I fixed it with init'ing with lazy.nvim when loading the function.  Hopefully this will help others.

```
 {
   "f-person/git-blame.nvim",
    init = function()
      vim.g.gitblame_message_template = ' <author> - <date> - <summary> - <sha>'
      vim.g.gitblame_enabled = 0
    end,
}
```

**Comment by f-person** [comment]
This is fixed now! You should switch to `setup`:
```lua
require("gitblame").setup { enabled = false }
```

Also opened a PR for LunarVim docs: https://github.com/LunarVim/lunarvim.org/pull/421
