### ISSUE TITLE
Relative date not showing on MacOS

### ISSUE THREAD

**Issue by camiloaromero23** [f-person/git-blame.nvim#66]
I don't know if this issue is related with MacOS because it was working before with the exact same configuration. The only thing I did was to change my package manager from `packer` to `lazy.nvim`. I've tried other date formats that worked, my guess is that it is only related to the relative date.

My git-blame configuration.

```lua
vim.g.gitblame_message_template = "      <author>, <date> • <summary>"
vim.g.gitblame_date_format = "%r"
vim.g.gitblame_ignored_filetypes = { "NvimTree", "netrw", "packer" }
vim.g.gitblame_set_extmark_options = {
  hl_mode = "combine",
  priority = 10000,
}
```

Screenshot of how blame is shown

<img width="802" alt="image" src="https://user-images.githubusercontent.com/64717266/211584654-77b63f07-cbeb-4c62-82eb-676f73aea3ea.png">

**Comment by f-person** [comment]
Hi! I guess the order of initializing stuff causes the issue. Basically, the relative date format check is done only on the plugin initialization. If you call `vim.g.gitblame_date_format = "%r"` after `git-blame.nvim` is initialized, it will have no effect. This can be solved from the plugin side by refactoring some stuff but for now, you can try to call `require('gitblame').init()` after the setup to temporarily fix the problem. Let me know if that helps and we'll keep the issue open until it's solved from the plugin side.

**Comment by camiloaromero23** [comment]
That worked out for me, thanks! 🙌🏽. I will be waiting for the bug solution, please @ me when it done to test it out. Thanks for your good work!

**Comment by f-person** [comment]
@camiloaromero23 I pushed the fix. Please try removing the `require('gitblame').init()` hack, updating the plugin and see if it's fixed for you now :)

**Comment by camiloaromero23** [comment]
It is working perfect, thanks!
