### ISSUE TITLE
Setup function for config?

### ISSUE THREAD

**Issue by lougreenwood** [f-person/git-blame.nvim#69]
Sorry if this is a dumb question, I'm still relatively new to nvim etc.

Is it possible to configure the plugin with a setup function instead of using the vim commands? e.g:

```
require("git-blame").setup {
  message_template = '<author>, <date> | <summary>'
}
```

All of my other plugins are configured something like this, like I said, I'm relatively new to nvim and also using a distro (`astronvim`) as a base - but I'm not sure if the above is more of a modern way to configure nvim plugins etc (see `telescope`, `cmp` etc).

Thanks again! 💙

**Comment by f-person** [comment]
Hi! Unfortunately, this isn't something that's supported at the moment. However, this is something worth doing at some point

**Comment by felipesere** [comment]
I would be keen on this too. 
At the moment, I get a stray git blame line at the top of the file even though I disable the plugin by default.
I bet its because it will render that faster than my config disables it 😅

**Comment by f-person** [comment]
@felipesere yeah, I want to add this eventually. I've been thinking about ways to add a setup function without breaking current configurations. There are ways to do that, but didn't get to it yet, heh :)
