### ISSUE TITLE
Date/Time Formatting

### ISSUE THREAD

**Issue by johnallen3d** [f-person/git-blame.nvim#7]
First let me say I love this plugin and it's worked flawlessly for me, thanks!

I've noticed two things about the date/time formatting though:

1) component parts are not zero padded, e.g. `1.1.2020, 9:8` rather than `01.01.2020, 09:08`
2) this might be just my opinion but I think it's common for devs to prefer the ISO 8601 format for date/time e.g. `2020-01-01`

I hacked the date/time formatting locally in order to address these two concerns of mine. I have zero lua experience so please forgive any convention violations.

```
        formatted_date = info.date.year .. '-'
                            .. string.format("%02d", info.date.month) .. '-'
                            .. string.format("%02d", info.date.day) .. ' '
                            .. string.format("%02d", info.date.hour) .. ':'
                            .. string.format("%02d", info.date.min)
``` 
<img width="912" alt="incent-gem: nvim README md — nvim 2020-11-17 10-49-41" src="https://user-images.githubusercontent.com/184915/99412388-a7dd5980-28c2-11eb-9dfd-687f18040f8d.png">

I'd be happy to open a PR if this change is of interest.

**Comment by f-person** [comment]
> First let me say I love this plugin and it's worked flawlessly for me, thanks!

Thanks for saying nice things :)

----

Customizable date format is something that definitely needs to be done. I also want to implement formatting with date-ago format. 

> component parts are not zero padded, e.g. 1.1.2020, 9:8 rather than 01.01.2020, 09:08
I'll replace this one in the default format.

> this might be just my opinion but I think it's common for devs to prefer the ISO 8601 format for date/time e.g. 2020-01-01
The default format is just how I've (and most people in my country) been writing dates for my entire life. However, I understand that the plugin needs to be configurable.

Two options of custom date formatting come to my mind - parsing a pattern from a string (more user-friendly) and letting others to overwrite a function responsible for date formatting (more flexible).
