### ISSUE TITLE
Template for not committed changes?

### ISSUE THREAD

**Issue by lougreenwood** [f-person/git-blame.nvim#70]
Hello,

I'm trying to configure the blame to match what I'm used to seeing in VSCode git lens.

I noticed that their message looks like this:

![Screenshot 2023-01-31 at 07 12 21](https://user-images.githubusercontent.com/12051736/215691372-57e7604c-4357-468f-9ff5-93c8ffd0f75b.png)

I tried to replicate this with the following config, but it seems that `gitblame_message_when_not_committed` doesn't support templates? Is there a different config to use templates for not committed changes?

```
vim.g.gitblame_message_when_not_committed = "     <author>, <date> • Uncommitted changes"
```

Thanks!

**Comment by f-person** [comment]
The message for uncommited changes is hardcoded at the moment. I'll check if I can get the date of uncommited changes. If yes, I'll add the template parser :)

**Comment by f-person** [comment]
Completed in 7aed504
