### ISSUE TITLE
Invalid Capture Index

### ISSUE THREAD

**Issue by TimOleSanmann** [f-person/git-blame.nvim#72]
Hey everybody, 
I suddenly get the following error message:
`Fehler beim Ausführen von "CursorMoved Autokommandos für "*"":
E5108: Error executing lua .../share/nvim/plugged/git-blame.nvim/lua/gitblame/init.lua:237: invalid capture index
stack traceback:
        [C]: in function 'gsub'
        .../share/nvim/plugged/git-blame.nvim/lua/gitblame/init.lua:237: in function 'get_blame_text'
        .../share/nvim/plugged/git-blame.nvim/lua/gitblame/init.lua:302: in function 'show_blame_info'
        [string ":lua"]:1: in main chunk`

After a short exploration, the pattern where this happens, is the strage commit message, which is "Fixed %2f in urls". Maybe there is a need to escape special charackters for those cases.

OS: macOS Ventura 13.1
Version:
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by f-person** [comment]
Hi! Thanks for the bug report! It's pretty weird; I'll look into it when I have some time :)

**Comment by TimOleSanmann** [comment]
Thank you :)
