### ISSUE TITLE
feat: blame information displays after a second or two...

### ISSUE THREAD

**Issue by fakeharxy** [f-person/git-blame.nvim#73]
Hello! Thanks for making and maintaining an awesome plugin.

My request seems so obvious I feel like I may be missing something obvious.

It would just be nice if the blame virtual text showed after a second or two so that when you're speeding up and down a doc it's not jumping with you the whole way.

I dunno, maybe nobody else wants that ¯\_(ツ)_/¯

cheers

**Comment by f-person** [comment]
Hi! Thanks for your kind words; very appreciated! This was also requested in discussion #67, and I'll implement it soon-ish.

**Comment by f-person** [comment]
Merged the feature earlier today. Let me know if this works for you :)
