### ISSUE TITLE
Disable virtual text on insert mode

### ISSUE THREAD

**Issue by iguiIllanes** [f-person/git-blame.nvim#77]
Awesome plugin! I've been using it for almost a week and I really like it.
I was wondering if there is a way to disable virtual text when insert mode is active?

I'm having issues with copilot suggestions and git-blame text overwriting on insert mode 

![ScreenShot 2023-04-06 at 18 33 24](https://user-images.githubusercontent.com/22847626/230505858-37f752a8-098e-4654-aefd-4ccfab224c79.png)

**Comment by f-person** [comment]
Hi! Thanks for using the plugin! As soon as you start typing, the virtual text will disappear. However, if you don't want the blame messages at all when in insert mode, you could set up an auto command that disables the plugin when entering insert mode. The plugin itself doesn't provide that functionality (at least, for now)
