### ISSUE TITLE
Plugin slows down file opening

### ISSUE THREAD

**Issue by smartding** [f-person/git-blame.nvim#8]
With this plugin enabled, I notice a delay when opening files in a git repo that contains 19k+ files. Less than a second, but noticeable. In smaller repos, the delay is not that obvious.

Is there any aysnc trick we can use to make this delay go away?

I'm on archlinux, NVIM v0.5.0-844-g8c4648421

**Comment by ecosse3** [comment]
I can also notice this perfomance issue. I think it's related to loading plugin on BufEnter. It's less than second but noticeable with larger files. I compared it when open the same file with plugin enabled and disabled.

I'm not much into making vim plugins but maybe there's some way to loads plugin asynchoneusly AFTER buffer is loaded.

**Comment by f-person** [comment]
> I think it's related to loading plugin on BufEnter

It's not loading the plugin, it's checking whether or not the file that was just opened is in a git repository using `git ls-files --error-unmatch filepath`. `show_blame_info` is asynchronous. I'll make the checking asynchronous too.

**Comment by f-person** [comment]
Can you please try the [file-open-performance](https://github.com/f-person/git-blame.nvim/tree/file-open-performance) and see if it's better now?

**Comment by ecosse3** [comment]
@f-person Yes, definitely it's better now! I compared without plugin, with master version and file-open-performance. It's still a little bit slower than without plugin but seems acceptable now.

**Comment by f-person** [comment]
I wonder if migrating all `vim.fn.system` calls to `vim.loop.spawn` will make the plugin *truly* asynchronous.

**Comment by f-person** [comment]
Yeah, I think the codebase needs to be fully migrated to libuv.

**Comment by f-person** [comment]
I migrated the codebase to libuv in #10. The plugin shouldn't now block cursor movement/user input in any way.
