### ISSUE TITLE
Handle new output from git blame command when using --contents

### ISSUE THREAD

**Issue by gunslingerfry** [f-person/git-blame.nvim#84]
Starting with git 2.4.1, using --contents git outputs "External file (--contents)" instead of "Not committed yet." This is an extremely bizarre decision because the command doesn't know the current state of the file on disk and therefore it cannot differentiate between changes that are truly 'not committed yet' and ones that are just in the temporary buffer passed in.

This breaks all 'real time' git blame plugins like git-blame.nvim.  git-blame.nvim should mitigate this change by replacing the output "External file (--contents)" with the previous message "Not committed yet." Additionally, git-blame will output a spurious date and commit message and should not be output. See attached image.

![20230624_14h33m41s_grim](https://github.com/f-person/git-blame.nvim/assets/4825657/e65fe988-6b6f-4936-a3ce-a2f61e94e32b)

Here is the commit of limited usefulness from git:
https://github.com/git/git/commit/603d0fdce2ca84d4dc7b26e46430778fe9c4cb72

**Comment by f-person** [comment]
Thanks for letting me know!
