### ISSUE TITLE
Horizontal movement clears, but doesn't redraw

### ISSUE THREAD

**Issue by aarondill** [f-person/git-blame.nvim#85]
Horizontal movement on a line clears the virtual text, but it's never redrawn.

In #1, you added a check for horizontal movement to simply abort, as nothing should change, however, later in 353d4a9cf45c9b404e34f612a8395b8e384144b1, you added [this line](https://github.com/f-person/git-blame.nvim/blob//lua/gitblame/init.lua#L368) which clears the virtual text, _even on horizontal movement_

This could be resolved by checking for horizontal movement in `schedule_show_info_display` instead of / in addition to `show_blame_info`. 

Note: this is _not_ an issue if `vim.g.gitblame_delay` is set to `0` or `nil`, as the delay code is never reached.

Potential implementation:

```lua
local function schedule_show_info_display()
    ---@type integer
    local delay = vim.g.gitblame_delay
    local filepath = utils.get_filepath()
    local line = utils.get_line_number()
    if not delay or delay == 0 then
        show_blame_info()
    elseif last_position.filepath ~= filepath or last_position.line ~= line then
        if delay_timer and vim.loop.is_active(delay_timer) then
            delay_timer:stop()
            delay_timer:close()
        end
        clear_virtual_text()
        delay_timer = vim.defer_fn(show_blame_info, delay)
    end
end
```

This implementation has a bug, in which switching from line `1` to `2` and back to `1` (example numbers) before the end of `delay` will stop the info from showing, but it's an example to get it started.

**Comment by f-person** [comment]
Thanks for the bug report! Should be fixed now!

**Comment by aarondill** [comment]
Thanks for the quick reply! It works great! The only issue is a forgotten debug print statement left in. See #86 for a pr removing it :smile:
