### ISSUE TITLE
GitBlameOpenFileURL on the current commit

### ISSUE THREAD

**Issue by haoyuan80s** [f-person/git-blame.nvim#87]
GitBlameOpenFileURL open url of the master. Is that possible to GitBlameOpenFileURL on the current commit?

**Comment by f-person** [comment]
There's `GitBlameOpenCommitURL`, which opens the specific commit where the change was made. Maybe that's what you are looking for? I can't picture a scenario where you wanna open the file in the *latest* commit

**Comment by f-person** [comment]
Makes sense! I'll tag this as enhancement and implement it at some point when I'm free
