### ISSUE TITLE
Plugin opens a lot of weird buffers when opening a new file with fzf.vim

### ISSUE THREAD

**Issue by ecosse3** [f-person/git-blame.nvim#9]
Hi,

after updating plugins few commits ago I have issue while working with larger projects with fzf.vim. When I open any file by fzf.vim when git-blame is enabled vim opens for me dozens of weird named buffers (which names regards to git-blame). It happens both on Linux and macOS. I'm running latest NVIM v0.5.0-828-g0a95549d6.

I upload gif demo.

![gitblame_issue](https://user-images.githubusercontent.com/17691791/99543951-0b937f80-29b4-11eb-8e17-8eb7e92ce595.gif)

With that problem I'm not able to use this plugin but I love it. Problem happens only when I have enabled git-blame.nvim in VimPlug.

Thanks.

**Comment by f-person** [comment]
Can you please provide minimal configuration with which the bug is reproducible?

**Comment by ecosse3** [comment]
> Can you please provide minimal configuration with which the bug is reproducible?

Sure. I was able to reproduce this with minimal config and looks like I found where is the problem. I'm not sure if it's a syntax problem but actually problem is with my **let g:fzf_colors = ...**. Without it this plugins works, wow.

Minimal config:
```
set nocompatible
filetype plugin indent on
syntax on
set hidden

call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'vim-airline/vim-airline'
Plug 'f-person/git-blame.nvim'
call plug#end()

let $FZF_DEFAULT_COMMAND="fd --hidden --type f --exclude .git"
let $FZF_DEFAULT_OPTS="--reverse || --preview '[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (bat --style=numbers --color=always {} || highlight -O ansi -l {} || coderay {} || rougify {} || cat {}) 2> /dev/null'"

let g:fzf_layout = { 'window': { 'width': 0.8, 'height': 0.8 } }
let g:fzf_nvim_statusline = 0

let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'Conditional', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'Conditional', 'Conditional'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

nnoremap <silent> <c-p> :Files<CR>

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1
```

To run this:
**nvim -u mini.vim**

**Comment by f-person** [comment]
Thanks, I can reproduce the bug now. It's strange, I'm debugging it to understand the cause now. I think it has something to do with git-blame.nvim doing its stuff on `BufEnter` event.

**Comment by f-person** [comment]
It happens on this autocommand https://github.com/f-person/git-blame.nvim/blob/7c14308fc581c6a7afc48d79c0a478ff788ce22f/plugin/gitblame.vim#L14
