### ISSUE TITLE
Disable gitblame by default doesn't work

### ISSUE THREAD

**Issue by OrteipX** [f-person/git-blame.nvim#90]
![Screenshot 2023-08-30 at 10 59 09 AM](https://github.com/f-person/git-blame.nvim/assets/28165423/924f3c1f-e255-4c68-86a2-8007b1f300b0)

setting `enabled = false` doesn't disable it, instead, when toggling it it "fails" then the next time starts to work.

Is there another way of not showing gitblame by default?

**Comment by f-person** [comment]
sounds like a bug, i'll check it. meanwhile, you can do `vim.g.gitblame_enabled = false`

**Comment by OrteipX** [comment]
sounds good,  thanks!!

**Comment by bossley9** [comment]
Now fixed in https://github.com/f-person/git-blame.nvim/pull/102! Not sure why this issue didn't automatically close
